/**
 * Auto-generated TypeScript type definitions for design tokens
 *
 * DO NOT EDIT MANUALLY - Generated by scripts/generateTypes.ts
 *
 * To regenerate: npm run build:types
 */

export type AnimationDurationType = "base" | "slow"
export type AnimationEasingType = "base"
export type BackgroundColorType = "base" | "alternate"
export type BorderColorType = "base" | "heavy" | "heavier"
export type BorderRadiusType = "smaller" | "small" | "base" | "large" | "larger"
export type BorderWidthType = "base" | "large"
export type BoxShadowType = "downBase" | "downLarge" | "upBase" | "upLarge"
export type CellHeightType = "smaller" | "small" | "base" | "large" | "larger"
export type ForegroundColorType = "lighter" | "light" | "medium" | "heavy" | "base" | "disabled" | "link" | "success" | "warning" | "error"
export type FontFamilyType = "base" | "code" | "heading"
export type FontSizeType = "smaller" | "small" | "base" | "large" | "larger"
export type FontWeightType = "light" | "base" | "medium" | "semibold" | "bold" | "extrabold" | "black"
export type GapType = "smaller" | "small" | "base" | "large" | "larger"
export type LineHeightType = "condensed" | "base" | "expanded"
