/**
 * Type definition writer.
 *
 * Emits src/generated/types.ts: a union type per core token group, plus
 * `ComponentPrefix` if any component prefixes exist.
 */

import * as fs from 'fs'
import type { TypeSources, TokenMap } from './readSources.js'

/**
 * Convert a camelCase token name into PascalCase for the type identifier.
 * `borderRadius` → `BorderRadius`, used as `BorderRadiusType`.
 */
function camelToPascal(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1)
}

/**
 * Build a single union-type line: `export type FontSizeType = "small" | "base" | ...`.
 */
function buildTokenUnionLine(tokenName: string, variants: Record<string, string>): string {
  const items = Object.keys(variants)
  const typeName = `${camelToPascal(tokenName)}Type`
  const unionType = items.map(key => `"${key}"`).join(' | ')
  return `export type ${typeName} = ${unionType}`
}

/**
 * Build the ComponentPrefix union line. Returns null when there are no prefixes
 * (which would produce an invalid `= ` syntax).
 */
function buildComponentPrefixLine(prefixes: string[]): string | null {
  if (prefixes.length === 0) return null
  const unionType = prefixes.map(p => `"${p}"`).join(' | ')
  return `export type ComponentPrefix = ${unionType}`
}

/**
 * Build the file header — `DO NOT EDIT` warning + regen command.
 */
function buildHeader(): string[] {
  return [
    '/**',
    ' * Auto-generated TypeScript type definitions for design tokens',
    ' *',
    ' * DO NOT EDIT MANUALLY - Generated by scripts/generateTypes/',
    ' *',
    ' * To regenerate: npm run build:types',
    ' */',
    '',
  ]
}

/**
 * Assemble the full lines array for the output file.
 */
function assembleLines(tokens: TokenMap, componentPrefixes: string[]): string[] {
  const lines: string[] = buildHeader()

  for (const tokenName of Object.keys(tokens)) {
    lines.push(buildTokenUnionLine(tokenName, tokens[tokenName]))
  }
  lines.push('')

  const prefixLine = buildComponentPrefixLine(componentPrefixes)
  if (prefixLine !== null) lines.push(prefixLine)
  lines.push('')

  return lines
}

/**
 * Write the assembled types.ts file and emit progress logs.
 */
export function writeTypesFile(sources: TypeSources, outputPath: string): void {
  const { tokens, componentPrefixes } = sources

  const lines = assembleLines(tokens, componentPrefixes)
  fs.writeFileSync(outputPath, lines.join('\n'), 'utf-8')

  console.log(`✓ Generated TypeScript types: ${outputPath}`)
  console.log(`✓ Generated ${Object.keys(tokens).length} core type definitions`)
  if (componentPrefixes.length > 0) {
    console.log(`✓ Generated ComponentPrefix: ${componentPrefixes.join(', ')}`)
  }
}
