/**
 * Apply breakpoint thresholds from a token map's `breakpoints` key.
 *
 * Validates the overrides, mutates `BREAKPOINTS` in place (so `getBreakpoint`,
 * `getBreakpointValue`, `breakpointKeyQuery`, and `useBreakpoint` read the new
 * values), and re-emits the generated breakpoint `@media` cascade — core
 * breakpoint tokens, component `$breakpoints` overrides, and component aliases
 * to core breakpoint tokens — into
 * `<style data-nice-breakpoints>` with the same emitters the build uses.
 *
 * Settable: every breakpoint in `SETTABLE_BREAKPOINTS` (positive numbers,
 * strictly ascending in breakpoint order). `phone` is the implicit base
 * (everything below the first settable floor) and cannot be set.
 *
 * Called by `generateTokenCSS` before it builds any CSS for the same call.
 * Runtime token CSS built by earlier calls is regenerated by `generateTokenCSS`,
 * not here — this module only re-emits the generated (build-time) cascade.
 *
 * @example
 * applyBreakpoints({ laptop: 1100 })  // true — BREAKPOINTS.laptop is 1100, cascade re-emitted
 * applyBreakpoints({ laptop: 1100 })  // false — unchanged, nothing re-emitted
 */

import breakpointTokensData from '../generated/breakpointTokensData.js'
import componentTokensData from '../generated/componentTokensData.js'
import componentBreakpointTokensData from '../generated/componentBreakpointTokensData.js'
import { generateBreakpointTokenCss } from './css/breakpointTokenCss.js'
import { generateComponentBreakpointCss } from './css/componentBreakpointTokenCss.js'
import { buildCoreScopeMap, generateComponentAliasCss } from './css/componentAliasCss.js'
import { declarationLine } from './css/declarations.js'
import { getConstantKey } from '../services/getConstant.js'
import { writeToken } from '../registry/createRegistry.js'
import { injectBreakpointCss } from './breakpointStyleSheet.js'
import {
  BREAKPOINTS,
  SETTABLE_BREAKPOINTS,
  type BreakpointValues,
  type SettableBreakpoint,
} from '../constants/breakpoints.js'

/**
 * Narrow a key of the `breakpoints` object to a settable breakpoint name.
 *
 * @param name - Key from the overrides object
 * @returns false for `phone` and unknown names
 */
function isSettable(name: string): name is SettableBreakpoint {
  return (SETTABLE_BREAKPOINTS as readonly string[]).includes(name)
}

/**
 * @param overrides - Partial pixel floors keyed by settable breakpoint
 * @returns true when any threshold changed (and the cascade was re-emitted)
 * @throws on an unknown or non-settable name, a non-positive or non-numeric
 *   value, or thresholds that are not strictly ascending after the merge
 */
export function applyBreakpoints(overrides: Partial<BreakpointValues>): boolean {
  // The value comes from an untyped token map at runtime, so check the shape first
  if (typeof overrides !== 'object' || overrides === null || Array.isArray(overrides)) {
    throw new Error('breakpoints: expected an object like { tablet: 700, laptop: 1100 }')
  }

  // Merge onto the current thresholds, validating each override
  const next: BreakpointValues = { ...BREAKPOINTS }
  for (const [name, value] of Object.entries(overrides)) {
    if (!isSettable(name)) {
      throw new Error(`breakpoints: "${name}" cannot be set. Settable breakpoints: ${SETTABLE_BREAKPOINTS.join(', ')}`)
    }
    if (typeof value !== 'number' || !Number.isFinite(value) || value <= 0) {
      throw new Error(`breakpoints: "${name}" must be a positive number of pixels (got ${JSON.stringify(value)})`)
    }
    next[name] = value
  }

  // Each floor must sit above the previous one in breakpoint order
  const ascending = SETTABLE_BREAKPOINTS.every((name, i) => i === 0 || next[SETTABLE_BREAKPOINTS[i - 1]] < next[name])
  if (!ascending) {
    throw new Error(
      `breakpoints: thresholds must ascend ${SETTABLE_BREAKPOINTS.join(' < ')} (got ${SETTABLE_BREAKPOINTS.map((name) => `${name} ${next[name]}`).join(', ')})`
    )
  }

  // Unchanged thresholds — nothing to mutate or re-emit
  const changed = SETTABLE_BREAKPOINTS.some((name) => BREAKPOINTS[name] !== next[name])
  if (!changed) return false

  // Mutate in place — the object reference is shared by every reader
  for (const name of SETTABLE_BREAKPOINTS) BREAKPOINTS[name] = next[name]

  // The floors are tokens too (`breakpoints:{name}`): update their runtime layer
  // so the getter reports the new value, and re-declare the custom properties
  for (const name of SETTABLE_BREAKPOINTS) {
    writeToken('runtime', { path: ['breakpoints'], variant: name }, `${BREAKPOINTS[name]}px`)
  }
  const thresholdBlock = [
    ':root {',
    ...SETTABLE_BREAKPOINTS.map((name) => declarationLine(getConstantKey(`breakpoints:${name}`), `${BREAKPOINTS[name]}px`)),
    '}',
  ]

  // Re-emit the generated breakpoint cascade at the new thresholds, in dist/tokens.css order:
  // core, component, then alias blocks. Authored component overrides suppress the alias line.
  // Only media blocks are needed: primitives in tokens.css hold values, which do not change.
  // Theme inputs are `{}` because only the breakpoint scopes are re-emitted.
  const core = generateBreakpointTokenCss(breakpointTokensData)
  const component = generateComponentBreakpointCss(componentTokensData, componentBreakpointTokensData)
  const alias = generateComponentAliasCss(
    componentTokensData,
    {},
    componentBreakpointTokensData,
    {},
    buildCoreScopeMap({}, breakpointTokensData, {})
  )
  // Replaces the previous override sheet; it follows tokens.css in <head>, so it wins
  injectBreakpointCss([...thresholdBlock, ...core.mediaBlocks, ...component.mediaBlocks, ...alias.bpMediaBlocks].join('\n'))
  return true
}
