/**
 * Token data writer.
 *
 * Emits four typed TypeScript files under src/generated/ — one per token source.
 * Each writer is a thin wrapper around writeFileWithHeader so the orchestrator
 * reads as a flat list of named writes.
 */

import * as fs from 'fs'
import * as path from 'path'
import type {
  TokenJsonSources,
  TokenMap,
  DimensionMap,
  ComponentTokensJson,
  BreakpointsJson,
} from './readSources.js'

/**
 * Write a TypeScript file that exports a typed constant from arbitrary JSON data.
 * Shared shape across every output: header comment, type defs, typed const, default export.
 */
function writeFileWithHeader(
  outputPath: string,
  sourceLabel: string,
  typeDefs: string,
  varName: string,
  varType: string,
  data: unknown
): void {
  const lines: string[] = [
    `/**`,
    ` * Auto-generated token data from ${sourceLabel}`,
    ` *`,
    ` * DO NOT EDIT MANUALLY - Generated by scripts/generateTokens/`,
    ` *`,
    ` * To regenerate: npm run build:tokens`,
    ` */`,
    ``,
    typeDefs,
    ``,
    `const ${varName}: ${varType} = ${JSON.stringify(data, null, 2)} as const`,
    ``,
    `export default ${varName}`,
  ]

  fs.writeFileSync(outputPath, lines.join('\n'), 'utf-8')
  console.log(`✓ Generated: ${outputPath}`)
}

/**
 * Emit src/generated/tokensData.ts from module.json (flat core tokens).
 */
function writeCoreTokens(generatedDir: string, data: TokenMap): void {
  writeFileWithHeader(
    path.join(generatedDir, 'tokensData.ts'),
    'tokens/modules',
    `export type TokenDefinition = Record<string, string>\n\nexport type TokensData = Record<string, TokenDefinition>`,
    'tokensData',
    'TokensData',
    data
  )
}

/**
 * Emit src/generated/themeTokensData.ts from module.themes.json (keyed by theme).
 */
function writeThemeTokens(generatedDir: string, data: DimensionMap): void {
  writeFileWithHeader(
    path.join(generatedDir, 'themeTokensData.ts'),
    'tokens/module.themes.json',
    `export type TokenDefinition = Record<string, string>\n\nexport type ThemeTokensData = Record<string, Record<string, TokenDefinition>>`,
    'themeTokensData',
    'ThemeTokensData',
    data
  )
}

/**
 * Emit src/generated/breakpointTokensData.ts from module.breakpoints.json (keyed by breakpoint).
 */
function writeBreakpointTokens(generatedDir: string, data: DimensionMap): void {
  writeFileWithHeader(
    path.join(generatedDir, 'breakpointTokensData.ts'),
    'tokens/module.breakpoints.json',
    `export type TokenDefinition = Record<string, string>\n\nexport type BreakpointTokensData = Record<string, Record<string, TokenDefinition>>`,
    'breakpointTokensData',
    'BreakpointTokensData',
    data
  )
}

/**
 * Emit src/generated/componentTokensData.ts from component.json day branch.
 */
function writeComponentTokens(generatedDir: string, data: ComponentTokensJson): void {
  writeFileWithHeader(
    path.join(generatedDir, 'componentTokensData.ts'),
    'tokens/component.json',
    `export type ComponentTokenNode = string | { [key: string]: ComponentTokenNode }\n\nexport type ComponentTokensData = Record<string, { [key: string]: ComponentTokenNode }>`,
    'componentTokensData',
    'ComponentTokensData',
    data
  )
}

/**
 * Emit src/generated/breakpointsData.ts from breakpoints.json (pixel thresholds).
 */
function writeBreakpoints(generatedDir: string, data: BreakpointsJson): void {
  writeFileWithHeader(
    path.join(generatedDir, 'breakpointsData.ts'),
    'tokens/breakpoints.json',
    `export type BreakpointsData = Record<string, number>`,
    'breakpointsData',
    'BreakpointsData',
    data
  )
}

/**
 * Emit all generated token data files.
 */
export function writeTokenDataFiles(sources: TokenJsonSources, generatedDir: string): void {
  writeCoreTokens(generatedDir, sources.core)
  writeThemeTokens(generatedDir, sources.color)
  writeBreakpointTokens(generatedDir, sources.size)
  writeComponentTokens(generatedDir, sources.component)
  writeBreakpoints(generatedDir, sources.breakpoints)
}
