/**
 * Token Data Generator
 *
 * Generates src/tokensData.ts from src/tokens/core/default/index.json
 * and src/componentTokensData.ts from src/tokens/component/{name}/index.json
 *
 * This script eliminates the need for JSON import assertions (assert/with)
 * which have compatibility issues with various bundlers (babel-loader, etc.)
 *
 * The generated files export the JSON data as typed TypeScript objects,
 * which can be imported normally by any bundler.
 *
 * @module generateTokens
 */

import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'
import { dirname } from 'path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

type TokensJson = Record<string, Record<string, string>>
type ComponentTokensJson = Record<string, Record<string, Record<string, string>>>

/**
 * Scan src/tokens/component/ for subdirectories containing index.json
 */
function loadComponentTokens(): ComponentTokensJson {
  const componentDir = path.join(__dirname, '..', 'src', 'tokens', 'component')
  const result: ComponentTokensJson = {}

  if (!fs.existsSync(componentDir)) {
    return result
  }

  const names = fs.readdirSync(componentDir)
  for (let i = 0; i < names.length; i++) {
    const name = names[i]
    const dirPath = path.join(componentDir, name)
    const stat = fs.statSync(dirPath)
    if (stat.isDirectory()) {
      const jsonPath = path.join(dirPath, 'index.json')
      if (fs.existsSync(jsonPath)) {
        result[name] = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'))
      }
    }
  }

  return result
}

/**
 * Generate tokensData.ts from core tokens and componentTokensData.ts from component tokens
 */
function main() {
  const tokensJsonPath = path.join(__dirname, '..', 'src', 'tokens', 'core', 'default', 'index.json')
  const tokensDataPath = path.join(__dirname, '..', 'src', 'generated', 'tokensData.ts')
  const componentTokensDataPath = path.join(__dirname, '..', 'src', 'generated', 'componentTokensData.ts')

  // Generate core tokensData.ts
  const tokensJson = fs.readFileSync(tokensJsonPath, 'utf-8')
  const tokens: TokensJson = JSON.parse(tokensJson)

  const lines: string[] = []
  lines.push(`/**`)
  lines.push(` * Auto-generated token data from tokens/core/default/index.json`)
  lines.push(` *`)
  lines.push(` * DO NOT EDIT MANUALLY - Generated by scripts/generateTokens.ts`)
  lines.push(` *`)
  lines.push(` * To regenerate: npm run build:tokens`)
  lines.push(` */`)
  lines.push(``)
  lines.push(`export type TokenDefinition = Record<string, string>`)
  lines.push(``)
  lines.push(`export type TokensData = Record<string, TokenDefinition>`)
  lines.push(``)
  lines.push(`const tokensData: TokensData = ${JSON.stringify(tokens, null, 2)} as const`)
  lines.push(``)
  lines.push(`export default tokensData`)

  fs.writeFileSync(tokensDataPath, lines.join('\n'), 'utf-8')
  console.log(`✓ Generated: ${tokensDataPath}`)

  // Generate componentTokensData.ts
  const componentTokens = loadComponentTokens()

  const cLines: string[] = []
  cLines.push(`/**`)
  cLines.push(` * Auto-generated component token data from tokens/component/{name}/index.json`)
  cLines.push(` *`)
  cLines.push(` * DO NOT EDIT MANUALLY - Generated by scripts/generateTokens.ts`)
  cLines.push(` *`)
  cLines.push(` * To regenerate: npm run build:tokens`)
  cLines.push(` */`)
  cLines.push(``)
  cLines.push(`export type ComponentTokenDefinition = Record<string, string>`)
  cLines.push(``)
  cLines.push(`export type ComponentTokensData = Record<string, Record<string, ComponentTokenDefinition>>`)
  cLines.push(``)
  cLines.push(`const componentTokensData: ComponentTokensData = ${JSON.stringify(componentTokens, null, 2)} as const`)
  cLines.push(``)
  cLines.push(`export default componentTokensData`)

  fs.writeFileSync(componentTokensDataPath, cLines.join('\n'), 'utf-8')
  console.log(`✓ Generated: ${componentTokensDataPath}`)
}

main()