/**
 * Token Data Generator
 *
 * Generates src/tokensData.ts from src/tokens.json
 *
 * This script eliminates the need for JSON import assertions (assert/with)
 * which have compatibility issues with various bundlers (babel-loader, etc.)
 *
 * The generated tokensData.ts exports the JSON data as a typed TypeScript object,
 * which can be imported normally by any bundler.
 *
 * @module generateTokens
 */

import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'
import { dirname } from 'path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

/**
 * Token definition structure from tokens.json
 */
interface TokenDefinition {
  name: string
  items: Record<string, string>
}

type TokensJson = Record<string, TokenDefinition>

/**
 * Generate tokensData.ts from tokens.json
 *
 * Reads the JSON file and outputs a TypeScript file that exports
 * the same data structure without requiring import assertions.
 */
function main() {
  const tokensJsonPath = path.join(__dirname, '..', 'src', 'tokens.json')
  const tokensDataPath = path.join(__dirname, '..', 'src', 'tokensData.ts')

  // Read and parse tokens.json
  const tokensJson = fs.readFileSync(tokensJsonPath, 'utf-8')
  const tokens: TokensJson = JSON.parse(tokensJson)

  // Generate TypeScript file content
  const lines: string[] = []

  lines.push(`/**`)
  lines.push(` * Auto-generated token data from tokens.json`)
  lines.push(` *`)
  lines.push(` * DO NOT EDIT MANUALLY - Generated by scripts/generateTokens.ts`)
  lines.push(` *`)
  lines.push(` * To regenerate: npm run build:tokens`)
  lines.push(` */`)
  lines.push(``)
  lines.push(`export interface TokenDefinition {`)
  lines.push(`  name: string`)
  lines.push(`  items: Record<string, string>`)
  lines.push(`}`)
  lines.push(``)
  lines.push(`export type TokensData = Record<string, TokenDefinition>`)
  lines.push(``)
  lines.push(`const tokensData: TokensData = ${JSON.stringify(tokens, null, 2)} as const`)
  lines.push(``)
  lines.push(`export default tokensData`)

  // Write the generated file
  fs.writeFileSync(tokensDataPath, lines.join('\n'), 'utf-8')
  console.log(`✓ Generated: ${tokensDataPath}`)
}

main()