/**
 * Token Data Generator
 *
 * Converts token JSON source files into typed TypeScript objects so they can
 * be imported by any bundler without JSON import assertions (assert/with).
 *
 * ## CLI
 *
 * ```bash
 * # One-shot build (used by npm run build:tokens)
 * node --loader ts-node/esm scripts/generateTokens.ts
 *
 * # Watch mode (used by npm run dev)
 * node --loader ts-node/esm scripts/generateTokens.ts --watch
 * ```
 *
 * ## Input
 *
 * - `src/tokens/core.json` — Flat core tokens: { group: { item: value } }
 * - `src/tokens/module.color.json` — Color module: { mode: { group: { item: value } } }
 * - `src/tokens/module.size.json` — Size module: { breakpoint: { group: { item: value } } }
 * - `src/tokens/component.json` — Component tokens (unchanged): { day: { prefix: { ... } }, night: { ... } }
 *
 * ## Output
 *
 * - `src/generated/tokensData.ts` — Core token data (flat)
 * - `src/generated/colorTokensData.ts` — Color module data (keyed by mode)
 * - `src/generated/sizeTokensData.ts` — Size module data (keyed by breakpoint)
 * - `src/generated/componentTokensData.ts` — Component token data (unchanged)
 *
 * @module generateTokens
 */

import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'
import { dirname } from 'path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

type TokenMap = Record<string, Record<string, string>>
type DimensionMap = Record<string, TokenMap>
type ComponentTokenNode = string | { [key: string]: ComponentTokenNode }
type ComponentTokensJson = Record<string, { [key: string]: ComponentTokenNode }>

/** Generate a TS file exporting a typed constant from JSON data */
function writeGeneratedFile(
  outputPath: string,
  sourceLabel: string,
  typeDefs: string,
  varName: string,
  varType: string,
  data: unknown
): void {
  const lines: string[] = [
    `/**`,
    ` * Auto-generated token data from ${sourceLabel}`,
    ` *`,
    ` * DO NOT EDIT MANUALLY - Generated by scripts/generateTokens.ts`,
    ` *`,
    ` * To regenerate: npm run build:tokens`,
    ` */`,
    ``,
    typeDefs,
    ``,
    `const ${varName}: ${varType} = ${JSON.stringify(data, null, 2)} as const`,
    ``,
    `export default ${varName}`,
  ]

  fs.writeFileSync(outputPath, lines.join('\n'), 'utf-8')
  console.log(`✓ Generated: ${outputPath}`)
}

function main() {
  const tokensDir = path.join(__dirname, '..', 'src', 'tokens')
  const generatedDir = path.join(__dirname, '..', 'src', 'generated')

  // --- Core tokens (flat: { group: { item: value } }) ---
  const coreJson: TokenMap = JSON.parse(
    fs.readFileSync(path.join(tokensDir, 'core.json'), 'utf-8')
  )
  writeGeneratedFile(
    path.join(generatedDir, 'tokensData.ts'),
    'tokens/core.json',
    `export type TokenDefinition = Record<string, string>\n\nexport type TokensData = Record<string, TokenDefinition>`,
    'tokensData',
    'TokensData',
    coreJson
  )

  // --- Color module (dimensioned: { mode: { group: { item: value } } }) ---
  const colorJson: DimensionMap = JSON.parse(
    fs.readFileSync(path.join(tokensDir, 'module.color.json'), 'utf-8')
  )
  writeGeneratedFile(
    path.join(generatedDir, 'colorTokensData.ts'),
    'tokens/module.color.json',
    `export type TokenDefinition = Record<string, string>\n\nexport type ColorTokensData = Record<string, Record<string, TokenDefinition>>`,
    'colorTokensData',
    'ColorTokensData',
    colorJson
  )

  // --- Size module (dimensioned: { breakpoint: { group: { item: value } } }) ---
  const sizeJson: DimensionMap = JSON.parse(
    fs.readFileSync(path.join(tokensDir, 'module.size.json'), 'utf-8')
  )
  writeGeneratedFile(
    path.join(generatedDir, 'sizeTokensData.ts'),
    'tokens/module.size.json',
    `export type TokenDefinition = Record<string, string>\n\nexport type SizeTokensData = Record<string, Record<string, TokenDefinition>>`,
    'sizeTokensData',
    'SizeTokensData',
    sizeJson
  )

  // --- Component tokens (unchanged: { day: { prefix: { ... } } }) ---
  const componentJson = JSON.parse(
    fs.readFileSync(path.join(tokensDir, 'component.json'), 'utf-8')
  )
  const componentTokens: ComponentTokensJson = componentJson.day
  writeGeneratedFile(
    path.join(generatedDir, 'componentTokensData.ts'),
    'tokens/component.json',
    `export type ComponentTokenNode = string | { [key: string]: ComponentTokenNode }\n\nexport type ComponentTokensData = Record<string, { [key: string]: ComponentTokenNode }>`,
    'componentTokensData',
    'ComponentTokensData',
    componentTokens
  )
}

main()

if (process.argv.includes('--watch')) {
  const tokensDir = path.join(__dirname, '..', 'src', 'tokens')
  let debounceTimer: ReturnType<typeof setTimeout> | null = null

  fs.watch(tokensDir, { recursive: true }, (_eventType, filename) => {
    if (!filename?.endsWith('.json')) return
    if (debounceTimer) clearTimeout(debounceTimer)
    debounceTimer = setTimeout(() => {
      console.log(`\nToken change detected: ${filename}`)
      try {
        main()
      } catch (error) {
        console.error('Error regenerating token data:', error)
      }
    }, 200)
  })

  console.log(`Watching ${tokensDir} for changes...`)
}
