/**
 * TypeScript Type Generator
 *
 * Generates union type definitions from token JSON source files so that
 * token groups and component prefixes are type-safe at compile time.
 *
 * ## CLI
 *
 * ```bash
 * # One-shot build (used by npm run build:types)
 * node --loader ts-node/esm scripts/generateTypes.ts
 *
 * # Watch mode (used by npm run dev)
 * node --loader ts-node/esm scripts/generateTypes.ts --watch
 * ```
 *
 * ## Input
 *
 * - `src/tokens/core.json` — Flat core tokens: { group: { item: value } }
 * - `src/tokens/component.json` — Component tokens: { day: { prefix: { ... } }, night: { ... } }
 *
 * ## Output
 *
 * - `src/generated/types.ts` — Union types for each core group + ComponentPrefix
 *
 * @module generateTypes
 */

import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'
import { dirname } from 'path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

function camelToPascal(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1)
}

function main() {
  const tokensDir = path.join(__dirname, '..', 'src', 'tokens')
  const outputPath = path.join(__dirname, '..', 'src', 'generated', 'types.ts')

  // Core tokens are now flat (no day/night wrapper)
  const tokens = JSON.parse(
    fs.readFileSync(path.join(tokensDir, 'core.json'), 'utf-8')
  )

  const lines: string[] = [
    '/**',
    ' * Auto-generated TypeScript type definitions for design tokens',
    ' *',
    ' * DO NOT EDIT MANUALLY - Generated by scripts/generateTypes.ts',
    ' *',
    ' * To regenerate: npm run build:types',
    ' */',
    '',
  ]

  // Generate a union type for each core token group
  for (const tokenName of Object.keys(tokens)) {
    const items = Object.keys(tokens[tokenName])
    const typeName = `${camelToPascal(tokenName)}Type`
    const unionType = items.map(key => `"${key}"`).join(' | ')
    lines.push(`export type ${typeName} = ${unionType}`)
  }

  lines.push('')

  // Component prefix type (unchanged — still reads component.json day keys)
  const componentJson = JSON.parse(
    fs.readFileSync(path.join(tokensDir, 'component.json'), 'utf-8')
  )
  const prefixes = Object.keys(componentJson.day)

  if (prefixes.length > 0) {
    const unionType = prefixes.map(p => `"${p}"`).join(' | ')
    lines.push(`export type ComponentPrefix = ${unionType}`)
  }

  lines.push('')

  fs.writeFileSync(outputPath, lines.join('\n'), 'utf-8')
  console.log(`✓ Generated TypeScript types: ${outputPath}`)
  console.log(`✓ Generated ${Object.keys(tokens).length} core type definitions`)
  if (prefixes.length > 0) {
    console.log(`✓ Generated ComponentPrefix: ${prefixes.join(', ')}`)
  }
}

main()

if (process.argv.includes('--watch')) {
  const tokensDir = path.join(__dirname, '..', 'src', 'tokens')
  let debounceTimer: ReturnType<typeof setTimeout> | null = null

  fs.watch(tokensDir, { recursive: true }, (_eventType, filename) => {
    if (!filename?.endsWith('.json')) return
    if (debounceTimer) clearTimeout(debounceTimer)
    debounceTimer = setTimeout(() => {
      console.log(`\nToken change detected: ${filename}`)
      try {
        main()
      } catch (error) {
        console.error('Error regenerating types:', error)
      }
    }, 200)
  })

  console.log(`Watching ${tokensDir} for changes...`)
}