/**
 * TypeScript Type Generator
 *
 * Generates TypeScript type definitions from token JSON files
 *
 * ## Purpose
 * Creates union types for all token groups (e.g., FontSizeType, ForegroundColorType)
 * and a ComponentPrefix union type from component token folder names.
 *
 * ## Input
 * - src/tokens/core/default/index.json: Core token definitions
 * - src/tokens/component/{name}/index.json: Component token definitions
 *
 * ## Output
 * - src/types.ts: TypeScript type definitions (compiled to dist by TypeScript)
 *
 * ## Example Output
 * export type FontSizeType = "smaller" | "small" | "base" | "large" | "larger"
 * export type ComponentPrefix = "button" | "icon" | "tile" | "typography"
 */

import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'
import { dirname } from 'path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

/**
 * Convert camelCase to PascalCase
 */
function camelToPascal(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1)
}

/**
 * Main execution function
 */
function main() {
  const tokensPath = path.join(__dirname, '..', 'src', 'tokens', 'core', 'default', 'index.json')
  const componentDir = path.join(__dirname, '..', 'src', 'tokens', 'component')
  const outputPath = path.join(__dirname, '..', 'src', 'types.ts')

  // Read core tokens
  const tokensContent = fs.readFileSync(tokensPath, 'utf-8')
  const tokens = JSON.parse(tokensContent)

  // Generate type definitions
  const lines: string[] = []
  lines.push('/**')
  lines.push(' * Auto-generated TypeScript type definitions for design tokens')
  lines.push(' *')
  lines.push(' * DO NOT EDIT MANUALLY - Generated by scripts/generateTypes.ts')
  lines.push(' *')
  lines.push(' * To regenerate: npm run build:types')
  lines.push(' */')
  lines.push('')

  // Generate a type for each core token group
  for (const tokenName of Object.keys(tokens)) {
    const token = tokens[tokenName]
    const items = Object.keys(token)
    const typeName = `${camelToPascal(tokenName)}Type`

    // Create union type from all item keys
    const unionType = items.map(key => `"${key}"`).join(' | ')

    lines.push(`export type ${typeName} = ${unionType}`)
  }

  lines.push('')

  // Generate ComponentPrefix type from component folder names
  const prefixes: string[] = []
  if (fs.existsSync(componentDir)) {
    const names = fs.readdirSync(componentDir)
    for (let i = 0; i < names.length; i++) {
      const name = names[i]
      const dirPath = path.join(componentDir, name)
      const stat = fs.statSync(dirPath)
      if (stat.isDirectory()) {
        const jsonPath = path.join(dirPath, 'index.json')
        if (fs.existsSync(jsonPath)) {
          prefixes.push(name)
        }
      }
    }
  }

  if (prefixes.length > 0) {
    const unionType = prefixes.map(p => `"${p}"`).join(' | ')
    lines.push(`export type ComponentPrefix = ${unionType}`)
  }

  lines.push('')

  // Write the file
  fs.writeFileSync(outputPath, lines.join('\n'), 'utf-8')
  console.log(`✓ Generated TypeScript types: ${outputPath}`)
  console.log(`✓ Generated ${Object.keys(tokens).length} core type definitions`)
  if (prefixes.length > 0) {
    console.log(`✓ Generated ComponentPrefix: ${prefixes.join(', ')}`)
  }
}

// Run the main function
main()