/**
 * Main Entry Point for nice-styles
 *
 * Seeds the token registry (side-effect import of `./init.js`), then re-exports
 * the public services, generated token types, layout and theme types, and the
 * raw generated data objects nice-react-styles consumes.
 *
 * ## Exports
 *
 * ### Token access
 * ```ts
 * import { getToken, listTokens } from 'nice-styles'
 * getToken('fontSize')                          // "var(--np--font-size)"
 * getToken('fontSize', 'large')                 // "var(--np--font-size--large)"
 * getToken('gap', 'base', { as: 'value' })      // "16px"
 * listTokens({ group: 'color' })                // every color variant, base and inverse
 * ```
 *
 * ### Types
 * One variant union per token group, plus component prefixes:
 * ```ts
 * import type { GapType, ColorType, ComponentPrefix } from 'nice-styles'
 * ```
 *
 * @module index
 */

// Initialize the token store — must run before any getter is called
import './init.js'

// Public services, constants, and their types (grouped in services/index.ts)
export {
  getBreakpoint,
  getBreakpointValue,
  parseBreakpointKey,
  breakpointKeyMatches,
  breakpointKeyRangeSize,
  compareBreakpointSpecificity,
  breakpointKeyQuery,
  isBreakpointName,
  isBreakpointKeyMap,
  BREAKPOINT_PHONE,
  BREAKPOINT_TABLET,
  BREAKPOINT_LAPTOP,
  BREAKPOINT_DESKTOP,
  BREAKPOINT_ORDER,
  SETTABLE_BREAKPOINTS,
  BREAKPOINTS,
  getToken,
  listTokens,
  resolveColorProp,
  getConstant,
  getConstantKey,
  NAMESPACE,
  transformColor,
  getTextHeight,
  camelToKebab,
  parseGoogleFontsUrl,
  parseAdobeFontsUrl,
  buildGoogleFontsConfig,
  buildAdobeFontsConfig,
  injectFontLinks,
  injectFonts,
  DEFAULT_THEME,
  DEFAULT_BREAKPOINT,
  STYLE_VALUE_KEYS,
  isStyleValue,
  registry,
  registerTokens,
  injectTokenCSS,
  generateTokenCSS,
  applyTheme,
} from './services/index.js'
export type {
  ThemeName,
  BreakpointName,
  BreakpointKey,
  BreakpointModifier,
  ParsedBreakpointKey,
  BreakpointValues,
  SettableBreakpoint,
  CssConstantOptions,
  TokenDefinition,
  TokenMap,
  ComponentTokenNode,
  ThemeValue,
  BreakpointValue,
  FontAxis,
  GoogleFontMetadata,
  LinkAttributes,
  GoogleFontsConfig,
  AdobeFontMetadata,
  AdobeFontsConfig,
  InjectFontsConfig,
  TransformColorOptions,
  StyleValueKind,
  TokenEntry,
  TokenValue,
  TokenLayer,
  TokenIdentity,
  TokenOptions,
  TokenAccessor,
  ColorTokenProp,
  ColorPropObject,
  ChannelValue,
  TokenListing,
  ListTokensFilter,
  TokenSource,
} from './services/index.js'

// Variant union types per token group, generated by build:types
export type {
  AnimationDurationType,
  AnimationEasingType,
  BackgroundColorType,
  BackgroundSizeType,
  BorderColorType,
  BorderRadiusType,
  BorderWidthType,
  BoxShadowType,
  ColorType,
  FontFamilyType,
  FontSizeType,
  FontWeightType,
  GapType,
  LetterSpacingType,
  LineHeightType,
  SizeType,
  ComponentPrefix,
} from './generated/types.js'

// Export layout types
export type {
  SpacingShorthandType,
  SpacingDefinitionType,
  SpacingResponsiveType,
  SpacingType,
} from './layoutTypes.js'

// Export theme types
export type { ThemeType } from './themeTypes.js'

// Export the raw tokens data — unthemed core groups + day theme values + phone
// breakpoint values, as one flat `{ group: { variant: value } }` object.
// Renamed from `Theme` to `Colors` to avoid collision with the <Theme>
// component exported from nice-react-styles. Despite the name, this object
// carries more than colors. nice-react-styles' StylesProvider passes it to
// styled-components' ThemeProvider as the theme object.
import tokensData from './generated/tokensData.js'
import themeTokensData from './generated/themeTokensData.js'
import breakpointTokensData from './generated/breakpointTokensData.js'
export const Colors = { ...tokensData, ...themeTokensData.day, ...breakpointTokensData.phone }

// Export component tokens data — component base trees keyed by prefix; re-exported by nice-react-styles
import componentTokensData from './generated/componentTokensData.js'
export { componentTokensData }

// Export raw theme and breakpoint token modules — dimension-keyed generated data:
// `{ theme: { group: { variant: value } } }` and `{ breakpoint: { group: { variant: value } } }`.
export { default as themeTokensData } from './generated/themeTokensData.js'
export { default as breakpointTokensData } from './generated/breakpointTokensData.js'
